openapi: "3.0.1"
info:
  title: "smartmssa-s3-object-access-api"
  version: "2023-11-09T17:00:01Z"
servers:
  - url: "s3access.internal.smartdev.ai/{basePath}"
    variables:
      basePath:
        default: ""
paths:
  /{bucketName}:
    post:
      description: "Get multiple public temporary URLs to access objects"
      parameters:
        - name: "bucketName"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestModel"
        required: true
      responses:
        "404":
          description: "404 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseModel"
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/postResponseModel"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseModel"
        "301":
          description: "301 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseModel"
        "500":
          description: "500 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseModel"
      security:
        - AccessS3ObjectsStackAccessS3ObjectsConstructbasicAuthorizerFC326EF4:
            []
    options:
      parameters:
        - name: "bucketName"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "204":
          description: "204 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
  /{bucketName}/{objectKey}:
    get:
      description: "Get public temporary URL to access a single object"
      parameters:
        - name: "bucketName"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "objectKey"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "404":
          description: "404 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseModel"
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getResponseModel"
        "400":
          description: "400 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseModel"
        "301":
          description: "301 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseModel"
        "500":
          description: "500 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponseModel"
      security:
        - AccessS3ObjectsStackAccessS3ObjectsConstructbasicAuthorizerFC326EF4:
            []
    options:
      parameters:
        - name: "bucketName"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "objectKey"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "204":
          description: "204 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
components:
  schemas:
    RequestModel:
      title: "objectsRequest"
      required:
        - "objects"
      type: "object"
      properties:
        objects:
          type: "array"
          items:
             type: string
    getResponseModel:
      title: "urlRequestModel"
      required:
        - "data"
        - "statusCode"
      type: "object"
      properties:
        data:
          type: "string"
    postResponseModel:
      title: "postResponseModel"
      required:
        - "data"
      type: "object"
      properties:
        data:
          type: "object"
    errorResponseModel:
      title: "errorResponseModel"
      required:
        - "message"
      type: "object"
      properties:
        message:
          type: "string"
  securitySchemes:
    AccessS3ObjectsStackAccessS3ObjectsConstructbasicAuthorizerFC326EF4:
      type: "apiKey"
      name: "Authorization"
      in: "header"
      x-amazon-apigateway-authtype: "custom"
